version: "3.1"

volumes:
  db: {}

services:
  tasker_db:
    image: postgres:11.6
    restart: always
    container_name: tasker_example_db
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: appuser
      POSTGRES_DB: tasker
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
